#!/bin/sh

echo "Running pre-push hook"

echo "
===============
|  Running detekt...
===============
"

./gradlew detekt --quiet

STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "
  ===============
  ❌ Detekt failed.
  ===============
  "
  exit 1
fi

echo "
===============
✔ Detekt passed.
===============
"

echo "
===================
|  Running ktLintCheck...
===================
"

./gradlew lint --quiet

STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "
  ===============
  ❌ Lint failed.
  ===============
  "
  exit 1
fi

echo "
===============
✔ Lint passed.
===============
"

exit 0
