#!/bin/sh

echo "Running pre-push hook"

echo "Running Detekt..."

./gradlew detekt --quiet

STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "❌ Detekt failed."
  exit 1
fi

echo "✔ Detekt passed."

echo "Running Lint..."

./gradlew lint --quiet

STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "❌ Lint failed."
  exit 1
fi

echo "✔ Lint passed."

exit 0
